# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-05 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='faqs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_content', models.TextField()),
                ('answer_content', models.TextField()),
                ('question_keywork', models.CharField(max_length=50)),
            ],
        ),
    ]
