# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-05 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ansdb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('problem_id', models.IntegerField(verbose_name='编程题序号')),
                ('language', models.IntegerField(verbose_name='编程题语言')),
                ('tokens', models.TextField(verbose_name='编程答案标记')),
            ],
        ),
    ]
