# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-11-02 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='allow_resubmit',
            field=models.BooleanField(default=True, verbose_name='是否允许重复提交作业>？'),
        ),
        migrations.AlterField(
            model_name='myhomework',
            name='allow_resubmit',
            field=models.BooleanField(default=True, verbose_name='是否允许重复提交作业？'),
        ),
    ]
