# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-10 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20180209_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='myhomework',
            name='allow_random',
            field=models.BooleanField(default=True, verbose_name='是否打乱选择题选项顺序？'),
        ),
    ]
