# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-15 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_auto_20180509_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='cause',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
