# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-14 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0004_remove_leave_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sign',
            old_name='status',
            new_name='type_of',
        ),
        migrations.AddField(
            model_name='sign',
            name='is_checked',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
