# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-08-04 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0006_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='sign',
        ),
        migrations.AddField(
            model_name='record',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sign.Event'),
            preserve_default=False,
        ),
    ]
