# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-08-04 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0007_auto_20180804_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='user',
        ),
    ]
